// Part-2/ionic7-react-sqlite-app/src/pages/UsersPage/UsersPage.tsx
import { useState, useEffect, useRef, useContext } from 'react';
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonCard,
        IonButtons, IonBackButton, useIonViewWillEnter, useIonViewWillLeave
      } from '@ionic/react';
import './UsersPage.css';
import UserForm from '../../components/UserForm/UserForm';
import UserList from '../../components/UserList/UserList';
import { User } from '../../models/User';
import { useQuerySQLite } from '../../hooks/UseQuerySQLite';
import { SQLiteDBConnection } from "@capacitor-community/sqlite";
import { platform } from '../../App';
import { SqliteServiceContext, StorageServiceContext } from '../../App';
import { Toast } from '@capacitor/toast';

const UsersPage: React.FC = () => {
  const ref = useRef(false);
  const dbNameRef = useRef('');
  const isInitComplete = useRef(false);
  const [users, setUsers] = useState<User[]>([]);
  const [db, setDb] = useState<SQLiteDBConnection | null>(null);
  const sqliteServ = useContext(SqliteServiceContext);
  const storageServ = useContext(StorageServiceContext);

  const openDatabase = () => {
    try {
      const dbUsersName = storageServ.getDatabaseName();
      dbNameRef.current = dbUsersName;
      const version = storageServ.getDatabaseVersion();

      sqliteServ.openDatabase(dbUsersName, version, false).then((database) => {
        setDb(database);
        ref.current = true;
      });
    } catch (error) {
      const msg = `Error open database:: ${error}`;
      console.error(msg);
      Toast.show({
        text: `${msg}`,
        duration: 'long'
      });           
    }
  }

  const handleAddUser = async (newUser: User) => {
    if (db) {
      // Send the newUser to the addUser storage service method
      const isConn = await sqliteServ.isConnection(dbNameRef.current,false);
      const lastId = await storageServ.addUser(newUser);
      newUser.id = lastId;

      // Update the users state to include the newly added user
      setUsers(prevUsers => [...prevUsers, newUser]);

    }
  };

  const handleUpdateUser = async (updUser: User) => {
    if (db) {
      const isConn = await sqliteServ.isConnection(dbNameRef.current,false);
      await storageServ.updateUserById(updUser.id.toString(),updUser.active);
      // Update the users state with the modified user
      setUsers(prevUsers =>
        prevUsers.map(user =>
          user.id === updUser.id ? { ...user, active: updUser.active } : user
        )
      );
    }
  };

  const handleDeleteUser = async (userId: number) => {
    if (db) {
      const isConn = await sqliteServ.isConnection(dbNameRef.current,false);
      await storageServ.deleteUserById(userId.toString());
      // Update the users state by filtering out the deleted user
      setUsers(prevUsers => prevUsers.filter(user => user.id !== userId));
   }
  };

  useIonViewWillEnter( () => {
    const initSubscription = storageServ.isInitCompleted.subscribe((value) => {
      isInitComplete.current = value;
      if(isInitComplete.current === true) {
        const dbUsersName = storageServ.getDatabaseName();
        if(ref.current === false) {
          if(platform === "web") {
            customElements.whenDefined('jeep-sqlite').then(() => {
              openDatabase();
            })
            .catch ((error) => {
              const msg = `Error open database:: ${error}`;
              console.log(`msg`);
              Toast.show({
                text: `${msg}`,
                duration: 'long'
              });           
            });

          } else {
            openDatabase();
          }
        }
      }
    });

    return () => {
      initSubscription.unsubscribe();
    };
  }, [storageServ]);

  useIonViewWillLeave(  () => {

      sqliteServ.closeDatabase(dbNameRef.current,false).then(() => {
        ref.current = false;  
      })
      .catch((error) => {
        const msg = `Error close database:: ${error}`;
        console.error(msg);
        Toast.show({
          text: `${msg}`,
          duration: 'long'
        });           
      });
    });
    useEffect(() => {
      // Fetch users from the database using useQuerySQLite hook

      if (isInitComplete.current === true && db) {
        const stmt = 'SELECT * FROM users';
        const values: any[] = [];
        const fetchData =  useQuerySQLite(db, stmt, values);
        fetchData()
        .then((fetchedUserData) => {
          setUsers(fetchedUserData);
        })
        .catch((error) => {
          const msg = `Error fetching user data: ${error}`;
          console.error(msg);
          Toast.show({
            text: `${msg}`,
            duration: 'long'
          });           
        });
      }
    }, [db]);


  return (
  <IonPage>
    <IonHeader>
      <IonToolbar>
        <IonTitle>Managing Users</IonTitle>
        <IonButtons slot="start">
          <IonBackButton text="home" defaultHref="/home"></IonBackButton>
        </IonButtons>
      </IonToolbar>
    </IonHeader>
    <IonContent>
      {ref.current && (
        <div>
          <IonCard>
            <h1>Add New User</h1>
            <UserForm onAddUser={handleAddUser} />
          </IonCard>
          <IonCard>
            <h2>Current Users</h2>
            <UserList users={users} onUpdateUser={handleUpdateUser} 
              onDeleteUser={handleDeleteUser}/>
          </IonCard>
        </div>
      )}
    </IonContent>
  </IonPage>
  );
};

export default UsersPage;

// SQLite/Part-1/quasar-sqlite-app/src/pages/UsersPage.vue
<template>
  <q-page>
    <div v-if="isInitComplete && dbInitialized">
      <q-card>
        <q-card-section>
          <div class="text-h5">Add New User</div>
          <user-form method="add" :onAddUser="handleAddUser"></user-form>
        </q-card-section>
      </q-card>
      <q-card>
        <q-card-section>
          <div class="text-h5">Current Users</div>
          <user-list
            :users="users"
            :onUpdateUserActive="handleUpdateUserActive"
            :onDeleteUser="handleDeleteUser"
            :onEditUser="handleEditUser"
          />
        </q-card-section>
      </q-card>
      <!-- q-dialog for the centered inline modal content -->
      <q-dialog v-model="centeredModalOpen">
        <q-card style="width: 60vw">
          <q-card-section>
            <!-- Modal content goes here -->
            <div class="text-h5">Update User</div>
            <user-form
              method="update"
              :onUpdateUser="handleUpdateUser"
              :user="editUser"
            ></user-form>
          </q-card-section>
        </q-card>
      </q-dialog>
    </div>
  </q-page>
</template>

<script lang="ts">
import {
  defineComponent,
  ref,
  inject,
  computed,
  onMounted,
  onBeforeUnmount,
  watch,
} from 'vue';
import UserForm from 'components/UserForm.vue';
import UserList from 'components/UserList.vue';
import { User } from '../models/User';
import { SQLiteDBConnection } from '@capacitor-community/sqlite';
import { Toast } from '@capacitor/toast';
import { useQuerySQLite } from '../hooks/UseQuerySQLite';
import SQLiteService from 'src/services/sqliteService';
import StorageService from 'src/services/storageService';

export default defineComponent({
  name: 'UsersPage',
  components: { UserForm, UserList },
  setup() {
    // Inject services
    const sqliteServ: SQLiteService | undefined = inject('sqliteServ');
    const storageServ: StorageService | undefined = inject('storageServ');
    // Define Internal variables
    const centeredModalOpen = ref(false);
    const centeredModalMarginTop = ref('20vh');
    const db = ref<SQLiteDBConnection | undefined>(undefined);
    const dbInitialized = computed(() => !!db.value);
    const dbNameRef = ref('');
    const editUser = ref<User>({} as User);
    const isInitComplete = ref(false);
    const isDatabase = ref(false);
    const platform = sqliteServ?.getPlatform();
    const users = ref<User[]>([]);

    // Define methods
    const getAllUsers = async (db: SQLiteDBConnection) => {
      // Query the database to get all users
      const stmt = 'SELECT * FROM users';
      const values: never[] = [];
      const fetchData = await useQuerySQLite(db, stmt, values);
      users.value = fetchData;
    };

    const openDatabase = async () => {
      // Open the connection to the database
      try {
        const dbUsersName = storageServ?.getDatabaseName() as string;
        dbNameRef.value = dbUsersName as string;
        const version = storageServ?.getDatabaseVersion() as number;

        const database = await sqliteServ?.openDatabase(
          dbUsersName,
          version,
          false
        );
        db.value = database;
        isDatabase.value = true;
      } catch (error) {
        const msg = `Error open database: ${error}`;
        console.error(msg);
        Toast.show({
          text: msg,
          duration: 'long',
        });
      }
    };

    const handleAddUser = async (newUser: User) => {
      // Store the new user in the database
      if (db.value) {
        const isConn = await sqliteServ?.isConnection(dbNameRef.value, false);
        if (!isConn) {
          const msg = 'Error handleAddUser: No DatabaseConnection';
          console.error(msg);
          Toast.show({
            text: msg,
            duration: 'long',
          });
        }
        const lastId = await storageServ?.addUser(newUser);
        newUser.id = lastId as number;
        users.value.push(newUser as never);
      }
    };

    const handleUpdateUser = async (updateUser: User) => {
      // Store the updated user data in the database
      if (db.value) {
        const isConn = await sqliteServ?.isConnection(dbNameRef.value, false);
        if (!isConn) {
          const msg = 'Error handleAddUser: No DatabaseConnection';
          console.error(msg);
          Toast.show({
            text: msg,
            duration: 'long',
          });
        }
        await storageServ?.replaceUser(updateUser);
        users.value = users.value.map((user) => {
          if (user.id === updateUser.id) {
            return { ...updateUser };
          } else {
            return user;
          }
        });
        console.log('handleUpdateUser users: ', JSON.stringify(users));
        centeredModalOpen.value = false;
      }
    };

    const handleUpdateUserActive = async (updUser: User) => {
      // Store the updated user's active field in the database
      if (db.value) {
        const isConn = await sqliteServ?.isConnection(dbNameRef.value, false);
        if (!isConn) {
          const msg = 'Error handleUpdateUser: No DatabaseConnection';
          console.error(msg);
          Toast.show({
            text: msg,
            duration: 'long',
          });
        }
        await storageServ?.updateUserActiveById(
          updUser.id.toString(),
          updUser.active
        );
        users.value = users.value.map((user: User) => {
          if (user.id === updUser.id) {
            // Clone the user and update the active property
            return { ...user, active: updUser.active };
          } else {
            return user;
          }
        });
      }
    };

    const handleDeleteUser = async (userId: number) => {
      // Delete a user from the database by using the id field
      if (db.value) {
        const isConn = await sqliteServ?.isConnection(dbNameRef.value, false);
        if (!isConn) {
          const msg = 'Error handleDeleteUser: No DatabaseConnection';
          console.error(msg);
          Toast.show({
            text: msg,
            duration: 'long',
          });
        }
        await storageServ?.deleteUserById(userId.toString());
        users.value = users.value.filter(
          (user) => (user as User).id !== userId
        );
      }
    };

    const handleEditUser = (user: User) => {
      // Get the user to update and open the modal edit form
      editUser.value = user;
      centeredModalOpen.value = true;
    };

    onMounted(() => {
      storageServ?.isInitCompleted.subscribe(async (value: boolean) => {
        isInitComplete.value = value;
        // Open the connection to the database
        if (isInitComplete.value === true) {
          if (platform === 'web') {
            // Web Plaform
            customElements
              .whenDefined('jeep-sqlite')
              .then(async () => {
                await openDatabase();
              })
              .catch((error) => {
                const msg = `Error open database: ${error}`;
                console.log(msg);
                Toast.show({
                  text: msg,
                  duration: 'long',
                });
              });
          } else {
            // Native Platforms
            await openDatabase();
          }
        }
      });
    });

    onBeforeUnmount(() => {
      // Close the connection to the database
      sqliteServ
        ?.closeDatabase(dbNameRef.value, false)
        .then(() => {
          isDatabase.value = false;
        })
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .catch((error: any) => {
          const msg = `Error close database:
                      ${error.message ? error.message : error}`;
          console.error(msg);
          Toast.show({
            text: msg,
            duration: 'long',
          });
        });
    });

    watch(isDatabase, (newIsDatabase) => {
      if (newIsDatabase) {
        // Get all users from the database
        getAllUsers(db.value as SQLiteDBConnection)
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          .catch((error: any) => {
            const msg = `close database:
                          ${error.message ? error.message : error}`;
            console.error(msg);
            Toast.show({
              text: msg,
              duration: 'long',
            });
          });
      } else {
        const msg = 'newDb is null';
        console.error(msg);
        Toast.show({
          text: msg,
          duration: 'long',
        });
      }
    });

    return {
      centeredModalMarginTop,
      centeredModalOpen,
      dbInitialized,
      editUser,
      isInitComplete,
      users,
      handleAddUser,
      handleDeleteUser,
      handleEditUser,
      handleUpdateUser,
      handleUpdateUserActive,
    };
  },
});
</script>
