// Part-2/ionic7-vue-sqlite-app/src/components/AppMenu.vue
<template>
    <ion-menu class="AppMenu" side="end" content-id="main-content">
      <ion-header>
        <ion-toolbar>
          <ion-title>Menu Content</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-content>
        <ion-list>
          <ion-item @click="closeMenu">
            <ion-button size="default" router-link="/users" expand="full">Managing Users</ion-button>
          </ion-item>
          <!-- ... other menu items -->
        </ion-list>
      </ion-content>
    </ion-menu>
</template>
  
<script lang="ts">
import { IonMenu, IonHeader, IonToolbar, IonTitle, IonContent, IonList,
        IonItem, IonButton } from '@ionic/vue';
import { defineComponent } from 'vue';
import { useIonRouter } from '@ionic/vue';

export default defineComponent({
    name: 'AppMenu',
    components: { IonMenu, IonHeader, IonToolbar, IonTitle, IonContent,
                IonList, IonItem, IonButton },
    setup() {
        const router = useIonRouter();
  
        const closeMenu = () => {
            const menu = document.querySelector('ion-menu');
            menu!.close();
        };
        return {closeMenu, router}
    },
});
</script>
<style scoped>
    .AppMenu  ion-button {
        --background: transparent;
        --color: initial;
        font-size: 18px;
    }
</style>

// SQLite/Part-1/typeorm-ionic7-react-sqlite-app/src/components/AppMenu/AppMenu.tsx
import React from 'react';
import './AppMenu.css';
import { IonMenu, IonHeader, IonToolbar, IonTitle, IonContent, IonLabel,
         IonList, IonItem, IonButton, IonItemGroup, IonItemDivider} from '@ionic/react';

interface AppMenuProps {}

const AppMenu: React.FC<AppMenuProps> = () => {
  const closeMenu = () => {
    const menu = document.querySelector('ion-menu');
    menu!.close();
  };
  return (
    <IonMenu className="AppMenu" side="end" contentId="main-content">
      <IonHeader>
        <IonToolbar>
          <IonTitle>Menu Content</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <IonList>
          <IonItemGroup>
            <IonItemDivider>
              <IonLabel class="menu-ion-label">Authors DB</IonLabel>
            </IonItemDivider>
            <IonItem onClick={closeMenu}>
              <IonButton size="default" routerLink="/authors" expand="full">Author's List</IonButton>
            </IonItem>
          </IonItemGroup>
          <IonItemGroup>
            <IonItemDivider>
              <IonLabel class="menu-ion-label">Users DB</IonLabel>
            </IonItemDivider>
            <IonItem onClick={closeMenu}>
              <IonButton size="default" routerLink="/users" expand="full">User's List</IonButton>
            </IonItem>
          </IonItemGroup>
          {/* ... other menu items */}
        </IonList>
      </IonContent>
    </IonMenu>
  )
};
export default AppMenu;
