// SQLite/Encryption/ionic7-vue-sqlite-app-encryption/src/components/AppIntroText.vue
<template>
    <div class="AppIntroText">
        <h3>
        Welcome to the Ionic7/Vue SQLite Database CRUD App Example Tutorial
        </h3>
        <h4>using @capacitor-community/sqlite</h4>
    </div>
</template>
  
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'AppIntroText',
});
</script>

<style scoped>
.AppIntroText {
    width: 100%;
    max-height: 200px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    text-align: center;
    margin-top: 5%;
}
</style>

// SQLite/Part-1/typeorm-ionic7-react-sqlite-app/src/components/AppIntroText/AppIntroText.tsx
import React from 'react';
import './AppIntroText.css';

interface AppIntroTextProps {}

const AppIntroText: React.FC<AppIntroTextProps> = () => (
  <div className="AppIntroText">
    <div id="app-intro-header">
      <h3>
        Welcome to the Ionic7/React/Vite TypeOrm SQLite Database App Example Tutorial
      </h3>
      <h4>using @capacitor-community/sqlite</h4>
    </div>
    <div id="app-intro-content">
      <p>The purpose is to demonstrate the basic setup of the App. </p>
      <p>The CRUD methods could be implemented from there</p>
    </div>
  </div>
);

export default AppIntroText;
