// SQLite/Part-1/ionic7-react-sqlite-app/src/pages/UsersPage/UsersPage.tsx
import { useState, useEffect, useRef, useContext } from 'react';
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonCard,
        IonButtons, IonBackButton, useIonViewWillEnter, useIonViewWillLeave
      } from '@ionic/react';
import './UsersPage.css';
import UserForm from '../../components/UserForm/UserForm';
import UserList from '../../components/UserList/UserList';
import { User } from '../../models/User';
import { useQuerySQLite } from '../../hooks/UseQuerySQLite';
import { SQLiteDBConnection } from "@capacitor-community/sqlite";
import { platform } from '../../App';
import { SqliteServiceContext, StorageServiceContext } from '../../App';
import { Toast } from '@capacitor/toast';

const UsersPage: React.FC = () => {
  const ref = useRef(false);
  const dbNameRef = useRef('');
  const isInitComplete = useRef(false);
  const [users, setUsers] = useState<User[]>([]);
  const [db, setDb] = useState<SQLiteDBConnection | null>(null);
  const sqliteServ = useContext(SqliteServiceContext);
  const storageServ = useContext(StorageServiceContext);

  const openDatabase = () => {
    try {
      const dbUsersName = storageServ.getDatabaseName();
      dbNameRef.current = dbUsersName;
      const version = storageServ.getDatabaseVersion();

      sqliteServ.openDatabase(dbUsersName, version, false).then((database) => {
        setDb(database);
        ref.current = true;
      });
    } catch (error) {
      const msg = `Error open database:: ${error}`;
      console.error(msg);
      Toast.show({
        text: `${msg}`,
        duration: 'long'
      });           
    }
  }

  const handleAddUser = async (newUser: User) => {
    if (db) {
      // Send the newUser to the addUser storage service method
      const isConn = await sqliteServ.isConnection(dbNameRef.current,false);
      const lastId = await storageServ.addUser(newUser);
      newUser.id = lastId;

      // Update the users state to include the newly added user
      setUsers(prevUsers => [...prevUsers, newUser]);

    }
  };

  const handleUpdateUser = async (updUser: User) => {
    if (db) {
      const isConn = await sqliteServ.isConnection(dbNameRef.current,false);
      await storageServ.updateUserById(updUser.id.toString(),updUser.active);
      // Update the users state with the modified user
      setUsers(prevUsers =>
        prevUsers.map(user =>
          user.id === updUser.id ? { ...user, active: updUser.active } : user
        )
      );
    }
  };

  const handleDeleteUser = async (userId: number) => {
    if (db) {
      const isConn = await sqliteServ.isConnection(dbNameRef.current,false);
      await storageServ.deleteUserById(userId.toString());
      // Update the users state by filtering out the deleted user
      setUsers(prevUsers => prevUsers.filter(user => user.id !== userId));
   }
  };

  useIonViewWillEnter( () => {
    const initSubscription = storageServ.isInitCompleted.subscribe((value) => {
      isInitComplete.current = value;
      if(isInitComplete.current === true) {
        const dbUsersName = storageServ.getDatabaseName();
        if(ref.current === false) {
          if(platform === "web") {
            window.addEventListener('beforeunload', (event) => {
    
              sqliteServ.closeDatabase(dbNameRef.current,false).then(() => {
                ref.current = false;  
              })
              .catch((error) => {
                const msg = `Error close database:: ${error}`;
                console.error(msg);
                Toast.show({
                  text: `${msg}`,
                  duration: 'long'
                });           
              });
            });        
            customElements.whenDefined('jeep-sqlite').then(() => {
              openDatabase();
            })
            .catch ((error) => {
              const msg = `Error open database:: ${error}`;
              console.log(`msg`);
              Toast.show({
                text: `${msg}`,
                duration: 'long'
              });           
            });

          } else {
            openDatabase();
          }
        }
      }
    });

    return () => {
      initSubscription.unsubscribe();
    };
  }, [storageServ]);

  useIonViewWillLeave(  () => {

      sqliteServ.closeDatabase(dbNameRef.current,false).then(() => {
        ref.current = false;  
      })
      .catch((error) => {
        const msg = `Error close database:: ${error}`;
        console.error(msg);
        Toast.show({
          text: `${msg}`,
          duration: 'long'
        });           
      });
    });
    useEffect(() => {
      // Fetch users from the database using useQuerySQLite hook

      if (isInitComplete.current === true && db) {
        const stmt = 'SELECT * FROM users';
        const values: any[] = [];
        const fetchData =  useQuerySQLite(db, stmt, values);
        fetchData()
        .then((fetchedUserData) => {
          setUsers(fetchedUserData);
        })
        .catch((error) => {
          const msg = `Error fetching user data: ${error}`;
          console.error(msg);
          Toast.show({
            text: `${msg}`,
            duration: 'long'
          });           
        });
      }
    }, [db]);


  return (
  <IonPage>
    <IonHeader>
      <IonToolbar>
        <IonTitle>Managing Users</IonTitle>
        <IonButtons slot="start">
          <IonBackButton text="home" defaultHref="/home"></IonBackButton>
        </IonButtons>
      </IonToolbar>
    </IonHeader>
    <IonContent>
      {ref.current && (
        <div>
          <IonCard>
            <h1>Add New User</h1>
            <UserForm onAddUser={handleAddUser} />
          </IonCard>
          <IonCard>
            <h2>Current Users</h2>
            <UserList users={users} onUpdateUser={handleUpdateUser} 
              onDeleteUser={handleDeleteUser}/>
          </IonCard>
        </div>
      )}
    </IonContent>
  </IonPage>
  );
};

export default UsersPage;

// SQLite/Part-1/ionic7-vue-sqlite-app/src/views/UsersPage.vue
<template>
    <ion-page>
      <ion-header>
        <ion-toolbar>
          <ion-title>Managing Users</ion-title>
          <ion-buttons slot="start">
            <ion-back-button text="home" default-href="/home"></ion-back-button>
          </ion-buttons>
        </ion-toolbar>
      </ion-header>
      <ion-content>
        <div v-if="isInitComplete && dbInitialized">
          <ion-card>
            <h1>Add New User</h1>
            <user-form :onAddUser="handleAddUser" />
          </ion-card>
          <ion-card>
            <h2>Current Users</h2>
            <user-list :users="users" :onUpdateUser="handleUpdateUser" :onDeleteUser="handleDeleteUser" />
          </ion-card>
        </div>
      </ion-content>
    </ion-page>
</template>
<script lang="ts">
import { defineComponent, ref, computed, getCurrentInstance, onMounted,
         onBeforeUnmount, watch, Ref } from 'vue';
import { useIonRouter } from '@ionic/vue';
import { IonPage, IonHeader, IonToolbar, IonButtons, IonBackButton, IonTitle,
         IonContent, IonCard} from '@ionic/vue';
import { Toast } from '@capacitor/toast';
import { User } from '@/models/User';
import UserForm from '@/components/UserForm.vue';
import UserList from '@/components/UserList.vue';
import { useQuerySQLite } from '@/hooks/UseQuerySQLite';
import { SQLiteDBConnection } from '@capacitor-community/sqlite';

export default defineComponent({
    name: 'TestPage',
    components: { IonPage, IonHeader, IonToolbar, IonButtons, IonBackButton, IonTitle,
         IonContent, IonCard, UserForm, UserList },
    setup() {
      const dbNameRef = ref('');
      const isInitComplete = ref(false);
      const isDatabase = ref(false);
      const users = ref<User[]>([]);
      const db = ref(null);
      const appInstance = getCurrentInstance();

      const router = useIonRouter();
  
      const sqliteServ = appInstance?.appContext.config.globalProperties.$sqliteServ;
      const storageServ = appInstance?.appContext.config.globalProperties.$storageServ;

      const dbInitialized = computed(() => !!db.value);
      const platform = sqliteServ.getPlatform();

      if(platform === "web") {
        window.addEventListener('beforeunload', (event) => {

          sqliteServ.closeDatabase(dbNameRef.value, false)
          .then(() => {
            isDatabase.value = false;
          }).catch((error: any) => {
            const msg = `Error close database:
                          ${error.message ? error.message : error}`;
            console.error(msg);
            Toast.show({
              text: msg,
              duration: 'long'
            });
          });
        });        
      }

      const getAllUsers = async (db: Ref<SQLiteDBConnection|null>) => {
        const stmt = 'SELECT * FROM users';
        const values: any[] = [];
        const fetchData = await useQuerySQLite(db, stmt, values);
        users.value = fetchData;         
       
      }

      const openDatabase = async () => {
        try {
          const dbUsersName = storageServ.getDatabaseName();
          dbNameRef.value = dbUsersName;
          const version = storageServ.getDatabaseVersion();
  
          const database = await sqliteServ.openDatabase(dbUsersName, version, false);
          db.value = database;
          isDatabase.value = true;
        } catch (error) {
          const msg = `Error open database: ${error}`;
          console.error(msg);
          Toast.show({
            text: msg,
            duration: 'long'
          });
        }
      };
      const handleAddUser = async (newUser: User) => {
        if (db.value) {
          const isConn = await sqliteServ.isConnection(dbNameRef.value, false);
          const lastId = await storageServ.addUser(newUser);
          newUser.id = lastId;
          users.value.push(newUser as never);
        }
      };
      const handleUpdateUser = async (updUser: User) => {
        if (db.value) {
          const isConn = await sqliteServ.isConnection(dbNameRef.value, false);
          await storageServ.updateUserById(updUser.id.toString(), updUser.active);
          users.value = users.value.map((user: User) => {
            if (user.id === updUser.id) {
              // Clone the user and update the active property
              return { ...user, active: updUser.active };
            } else {
              return user;
            }
          });
        }
      };
  
      const handleDeleteUser = async (userId: number) => {
        if (db.value) {
          const isConn = await sqliteServ.isConnection(dbNameRef.value, false);
          await storageServ.deleteUserById(userId.toString());
          users.value = users.value.filter(user => (user as User).id !== userId);
        }
      };
      onMounted(() => {
        const initSubscription = storageServ.isInitCompleted.subscribe(async (value: boolean) => {
          isInitComplete.value = value;
          if (isInitComplete.value === true) {
            const dbUsersName = storageServ.getDatabaseName();
            if (platform === "web") {
              customElements.whenDefined('jeep-sqlite').then(async () => {
                await openDatabase();
              }).catch((error) => {
                const msg = `Error open database: ${error}`;
                console.log(msg);
                Toast.show({
                  text: msg,
                  duration: 'long'
                });
              });
            } else {
              await openDatabase();
            }
          }
        });
      });
      onBeforeUnmount(() => {
          sqliteServ.closeDatabase(dbNameRef.value, false)
          .then(() => {
            isDatabase.value = false;
          }).catch((error: any) => {
            const msg = `Error close database:
                          ${error.message ? error.message : error}`;
            console.error(msg);
            Toast.show({
              text: msg,
              duration: 'long'
            });
          });
      });

      watch(isDatabase, (newIsDatabase) => {
        if (newIsDatabase) {
          getAllUsers(db).then(() => {

          })
          .catch((error: any) => {
            const msg = `close database:
                          ${error.message ? error.message : error}`;
            console.error(msg);
            Toast.show({
              text: msg,
              duration: 'long'
            });
          });         
        } else {
          const msg = `newDb is null`;
          console.error(msg);
          Toast.show({
              text: msg,
              duration: 'long'
            });
        }
      });

      return {isInitComplete, dbInitialized, users, handleAddUser,
              handleUpdateUser, handleDeleteUser}
    },
});
</script>
