// Part-2/ionic7-react-sqlite-app/src/components/AppIntroText/AppIntroText.tsx
import React, { FC } from 'react';
import './AppIntroText.css';

interface AppIntroTextProps {}

const AppIntroText: FC<AppIntroTextProps> = () => (
  <div className="AppIntroText">
    <h3>
      Welcome to the Ionic7/React SQLite Database CRUD App Example Tutorial
    </h3>
    <h4>using @capacitor-community/sqlite</h4>
  </div>
);

export default AppIntroText;

// SQLite/Part-1/quasar-sqlite-app/src/components/AppIntroText.vue
<template>
  <div class="AppIntroText">
    <h3>Welcome to the Quasar SQLite Database CRUD App Example Tutorial</h3>
    <h5>using @capacitor-community/sqlite</h5>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'AppIntroText',
});
</script>

<style scoped>
.AppIntroText {
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
  padding: 0.5rem;
}
</style>
