// SQLite/Part-2/ionic7-react-sqlite-app/src/components/UserList/UserList.tsx
import { FC } from 'react';
import './UserList.css';
import { IonList, IonItem, IonCheckbox, IonButton, IonIcon, IonLabel } from '@ionic/react';
import { User } from '../../models/User';
import { trash } from 'ionicons/icons'; // Import the trash icon

interface UserListProps {
  users: User[],
  onUpdateUser: (user: User) => void;
  onDeleteUser: (userId: number) => void; }

const UserList: FC<UserListProps> = ({users, onUpdateUser, onDeleteUser}) => {
  const handleCheckboxChange = (user: User) => {
    // Create a new user object with the updated active value
    const updatedUser = { ...user, active: user.active === 1 ? 0 : 1 };
    onUpdateUser(updatedUser);
  };

  return (
    <IonList className="UserList">
      {users.map((user: User) => (
          <IonItem key={user.id}>
            <IonCheckbox
              slot="start"
              aria-label=""
              checked={user.active === 1}
              onIonChange={() => handleCheckboxChange(user)}
            ></IonCheckbox>
              {user.id} - {user.name}
            <IonButton
            slot="end"
            fill="clear"
            color="danger"
            onClick={() => onDeleteUser(user.id)}
            >
              <IonIcon icon={trash} />
            </IonButton>
          </IonItem>
      ))}
    </IonList>
  )
};

export default UserList;

// SQLite/Part-2/quasar-sqlite-app/src/components/UserList.vue
<template>
  <q-list>
    <q-item v-for="user in users" :key="user.id">
      <q-item-section side middle>
        <q-checkbox
          :model-value="userActiveState(user)"
          dense
          @click="handleCheckboxClick(user)"
        />
      </q-item-section>
      <q-item-section>
        <q-item-label> {{ user.id }} - {{ user.name }} </q-item-label>
        <!-- <q-item-label> {{ user.email }} </q-item-label> // version 2 -->
      </q-item-section>
      <q-item-section side middle>
        <q-btn
          dense
          flat
          icon="edit"
          color="positive"
          @click="handleEditClick(user)"
        />
      </q-item-section>

      <!-- Delete Button with Trash Icon -->
      <q-item-section side middle>
        <q-btn
          dense
          flat
          icon="delete"
          color="negative"
          @click="handleDeleteClick(user.id)"
        />
      </q-item-section>
    </q-item>
  </q-list>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import { User } from '../models/User';

export default defineComponent({
  name: 'UserList',
  props: {
    users: Array as () => User[],
    onUpdateUserActive: Function,
    onDeleteUser: Function,
    onEditUser: Function,
  },
  setup(props) {
    const userActiveState = (user: User) => {
      // Convert user.active to boolean
      return user.active === 1;
    };
    const handleCheckboxClick = (user: User) => {
      // Create a new user object with the updated active value
      const updatedUser = { ...user, active: user.active === 1 ? 0 : 1 };
      if (typeof props.onUpdateUserActive === 'function') {
        props.onUpdateUserActive(updatedUser);
      }
    };
    const handleDeleteClick = (userId: number) => {
      if (typeof props.onDeleteUser === 'function') {
        props.onDeleteUser(userId);
      }
    };
    const handleEditClick = (user: User) => {
      if (typeof props.onEditUser === 'function') {
        props.onEditUser(user);
      }
    };

    return {
      userActiveState,
      handleCheckboxClick,
      handleDeleteClick,
      handleEditClick,
    };
  },
});
</script>
