// Encryption/ionic7-vue-sqlite-app-encryption/src/components/UserForm.vue
<template>
    <div class="UserForm">
      <ion-input
        ref="ionNameEl"
        :value="nameModel"
        @ionInput="handleNameInput($event)"
        type="text"
        placeholder="Rose Miller"
      ></ion-input>
      <!-- version 2
      <ion-input
        ref="ionEmailEl"
        :value="emailModel"
        @ionInput="handleEmailInput($event)"
        type="email"
        placeholder="Email"
      ></ion-input>
      -->
      <ion-button expand="block" shape="round" @click="handleSubmit" :disabled="!isFormValid">
        Add User
      </ion-button>
    </div>
</template>
  
<script lang="ts">
  import { ref } from 'vue';
  import { defineComponent, watch } from 'vue';
  import { IonInput, IonButton } from '@ionic/vue';
 
  export default defineComponent({
    name: 'UserForm',
    props: {
      onAddUser: Function,
    },
    components: {IonInput, IonButton},
    setup(props) {
        const ionNameEl = ref();
        const nameModel = ref('');
        const ionEmailEl = ref();
        const emailModel = ref('');
        const isFormValid = ref(false);
  
        const handleNameInput = (ev: { target: any; }) => {
            const value = ev.target!.value;
            const fileterdValue = value.replace(/[^a-zA-Z0-9-' ']+/g, '');
            nameModel.value = value;
    
            const inputCmp = ionNameEl.value;
            if (inputCmp !== undefined) {
                inputCmp.$el.value  = fileterdValue;
            }
        };
        /* Version 2
        const handleEmailInput = (ev:  { target: any; }) => {
            const value = ev.target!.value;

            // Update both the state variable and
            // the component to keep them in sync.

            emailModel.value = value;

            const inputCmp = ionEmailEl.value;
            if (inputCmp !== null) {
                inputCmp.$el.value = value;
            }

        };
        */    
        const handleSubmit = () => {
            if (nameModel.value /*&& emailModel.value */) {
                const newUser = {
                    id: Date.now(), // do not care about the id value (generated by sqlite)
                    name: nameModel.value,
                    active: 1,
                    /* email: emailModel.value, // version 2 */
                };
                if (typeof props.onAddUser === 'function') {
                    props.onAddUser(newUser);
                }
           
                nameModel.value = '';
                /* emailModel.value = ''; // version 2 */
                isFormValid.value = false;
            }
        };
  
      const hasTwoWords = (input: string) => {
        const words = input.trim().split(' ');
        return words.length === 2 && words.every((word) => word !== '');
      };
  
      /* Version 2
      const isValidEmail = (email) => {
        if (email.length === 0) {
          return false;
        }
        const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{1,}$/;
        return emailRegex.test(email);
      };
      */
        // Watch 'name' and 'email' for changes and update 'isFormValid'
        watch([nameModel/*, emailModel*/], ([newName/*, newEmail*/]) => {
            isFormValid.value = hasTwoWords(newName) /* && isValidEmail(newEmail)*/;
        });  
  
      return {
        ionNameEl,
        nameModel,
        /* emailModel, */
        isFormValid,
        handleNameInput,
        /*handleEmailInput,*/
        handleSubmit,
      };
    },
  });
</script>

// Part-1/ionic7-react-sqlite-app/src/components/UserForm/UserForm.tsx
import { FC, useState, useEffect, useRef } from 'react';
import { User } from '../../models/User';
import { IonInput, IonButton } from '@ionic/react';

import './UserForm.css';

interface UserFormProps {
  onAddUser: (user: User) => void;
}

const UserForm: FC<UserFormProps> = ({ onAddUser }) => {
  const isFormValid = useRef(false);
  const [name, setName] = useState('');
  const ionNameEl = useRef<HTMLIonInputElement>(null);

  /* for database Version 2
  const [email, setEmail] = useState('');
  const ionEmailEl = useRef<HTMLIonInputElement>(null);
  */

  const handleNameInput = (ev: Event) => {
    const value = (ev.target as HTMLIonInputElement).value as string;

    // Removes non alphanumeric characters
    const filteredValue = value.replace(/[^a-zA-Z0-9-' ']+/g, '');

    // Update both the state variable and
    //  the component to keep them in sync.
    setName(filteredValue);

    const inputCmp = ionNameEl.current;
    if (inputCmp !== null) {
      inputCmp.value = filteredValue;
    }

  };
  /* Version 2
  const handleEmailInput = (ev: Event) => {
    const value = (ev.target as HTMLIonInputElement).value as string;


    // Update both the state variable and
    // the component to keep them in sync.

    setEmail(value);

    const inputCmp = ionNameEl.current;
    if (inputCmp !== null) {
      inputCmp.value = value;
    }

  };
  */  

  const handleSubmit = () => {
    if (name /*&& email */) {
      const newUser: User = {
        id: Date.now(), // do not care about the id value (generated by sqlite)
        name,
        active: 1,
        /*email, //version 2 */
      };

      onAddUser(newUser);

      setName('');
      /*setEmail('');  // version 2 */
      isFormValid.current = false;
    }
  };
  const hasTwoWords = (input: string): boolean => {
    // Split the input string by spaces
    const words = input.trim().split(' ');

    // Check if there are exactly two non-empty words
    const isTwo = words.length === 2 && words.every(word => word !== '');
    return isTwo;
  }

  /* Version 2
  const isValidEmail = (email: string): boolean => {
    if(email.length === 0){
      return false;
    }
    const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{1,}$/;
    const test = emailRegex.test(email);
    return test;
  }
  */
  useEffect(()=> {
    isFormValid.current = hasTwoWords(name)/* && isValidEmail(email) // version 2*/ ;
  }, [name /*, email // version 2*/]);

  return (
    <div className="UserForm">
      <IonInput
        ref={ionNameEl}
        type="text"
        value={name}
        onIonInput={handleNameInput}
        placeholder="Rose Miller"
      ></IonInput>
      {/* version 2
        <IonInput
          ref={ionEmailEl}
          type="email"
          value={email}
          onIonInput={handleEmailInput}
          placeholder="Email"
        ></IonInput>
      */}
      <IonButton expand="full" onClick={handleSubmit} disabled={!isFormValid.current}>
        Add User
      </IonButton>
    </div>
  )
};

export default UserForm;
