// SQLite/Part-2/ionic7-react-sqlite-app/src/components/UserList/UserList.tsx
import { FC } from 'react';
import './UserList.css';
import { IonList, IonItem, IonCheckbox, IonButton, IonIcon, IonLabel } from '@ionic/react';
import { User } from '../../models/User';
import { trash } from 'ionicons/icons'; // Import the trash icon

interface UserListProps {
  users: User[],
  onUpdateUser: (user: User) => void;
  onDeleteUser: (userId: number) => void; }

const UserList: FC<UserListProps> = ({users, onUpdateUser, onDeleteUser}) => {
  const handleCheckboxChange = (user: User) => {
    // Create a new user object with the updated active value
    const updatedUser = { ...user, active: user.active === 1 ? 0 : 1 };
    onUpdateUser(updatedUser);
  };

  return (
    <IonList className="UserList">
      {users.map((user: User) => (
          <IonItem key={user.id}>
            <IonCheckbox
              slot="start"
              aria-label=""
              checked={user.active === 1}
              onIonChange={() => handleCheckboxChange(user)}
            ></IonCheckbox>
              {user.id} - {user.name}
            <IonButton
            slot="end"
            fill="clear"
            color="danger"
            onClick={() => onDeleteUser(user.id)}
            >
              <IonIcon icon={trash} />
            </IonButton>
          </IonItem>
      ))}
    </IonList>
  )
};

export default UserList;

// SQLite/Encryption/ionic7-vue-sqlite-app-encryption/src/components/UserList.vue
<template>
    <ion-list class="UserList">
      <ion-item v-for="user in users" :key="user.id">
        <ion-checkbox
          ref="ionActiveEl"
          slot="start"
          :checked="user.active==1 ? true: false"
          :activeModel="user.active"
          @ionChange="handleCheckboxChange(user)"
        ></ion-checkbox>
          {{ user.id }} - {{ user.name }}
        <ion-button
          slot="end"
          fill="clear"
          color="danger"
          @click="handleDeleteUser(user.id)"
        >
          <ion-icon :icon="trash" />
        </ion-button>
      </ion-item>
    </ion-list>
</template>
  
<script lang="ts">
    import { defineComponent, ref } from 'vue';
    import { IonList, IonItem, IonCheckbox, IonButton, IonIcon, IonLabel } from '@ionic/vue';
    import { User } from '@/models/User';
    import { trash } from 'ionicons/icons';
  
  
    export default defineComponent({
        name: 'UserList',
        props: {
            users: Array as () => User[],
            onUpdateUser: Function,
            onDeleteUser: Function
        },
        components: { IonList, IonItem, IonCheckbox, IonButton, IonIcon, IonLabel },
        setup(props) {
            const ionActiveEl = ref();
            const handleCheckboxChange = (user: User) => {
                // Create a new user object with the updated active value
                const updatedUser = { ...user, active: user.active === 1 ? 0 : 1 };
                if (typeof props.onUpdateUser === 'function') {
                    props.onUpdateUser(updatedUser);
                }
            };
            const handleDeleteUser = (userId: number) => {
                if (typeof props.onDeleteUser === 'function') {
                    props.onDeleteUser(userId);
                }
            }
            return {
                handleCheckboxChange, handleDeleteUser, trash
            };
        },
    });
</script>
